-- SnowOps AI POC
-- 01_setup.sql
-- Creates the Snowflake objects and a synthetic schema-drift incident.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SNOWOPS_DB;
CREATE SCHEMA IF NOT EXISTS SNOWOPS_DB.OPERATIONS;

CREATE OR REPLACE WAREHOUSE SNOWOPS_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SNOWOPS_WH;
USE DATABASE SNOWOPS_DB;
USE SCHEMA OPERATIONS;


CREATE OR REPLACE TABLE PIPELINES (
    PIPELINE_ID INTEGER,
    PIPELINE_NAME VARCHAR,
    OWNER_TEAM VARCHAR,
    PIPELINE_STATUS VARCHAR
);


CREATE OR REPLACE TABLE PIPELINE_RUNS (
    RUN_ID INTEGER,
    PIPELINE_ID INTEGER,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    RUN_STATUS VARCHAR,
    ERROR_MESSAGE VARCHAR,
    ROWS_PROCESSED INTEGER
);


CREATE OR REPLACE TABLE SCHEMA_CHANGES (
    CHANGE_ID INTEGER,
    TABLE_NAME VARCHAR,
    COLUMN_NAME VARCHAR,
    CHANGE_TYPE VARCHAR,
    OLD_VALUE VARCHAR,
    NEW_VALUE VARCHAR,
    CHANGE_TIME TIMESTAMP_NTZ
);


INSERT INTO PIPELINES VALUES
    (1, 'customer_ingestion', 'DATA_ENGINEERING', 'ACTIVE'),
    (2, 'revenue_etl', 'FINANCE_DATA', 'ACTIVE'),
    (3, 'inventory_sync', 'SUPPLY_CHAIN', 'ACTIVE');


INSERT INTO PIPELINE_RUNS VALUES
    (
        1001,
        2,
        '2026-09-07 09:00:00',
        '2026-09-07 09:03:24',
        'SUCCESS',
        NULL,
        1254300
    ),
    (
        1002,
        2,
        '2026-09-07 10:00:00',
        '2026-09-07 10:00:12',
        'FAILED',
        'SQL compilation error: invalid identifier CUSTOMER_SEGMENT',
        0
    );


INSERT INTO SCHEMA_CHANGES VALUES
    (
        501,
        'CUSTOMER_MASTER',
        'CUSTOMER_SEGMENT',
        'COLUMN_RENAME',
        'CUSTOMER_SEGMENT',
        'SEGMENT_NAME',
        '2026-09-07 09:35:00'
    );


-- Verification
SELECT * FROM PIPELINES;
SELECT * FROM PIPELINE_RUNS;
SELECT * FROM SCHEMA_CHANGES;
